#!/bin/bash
# author : lordpax
# rmc v1.0.0
# Supprime le contenu des dossiers et des sous-dossiers sans supprimer les dossiers eux-même

# explore <dir>
function explore() {
    [ "$1" == "" ] && echo "Usage: rmc <dir>" && exit 1
    [ ! -d "$1" ] && echo "ERROR: Directory \"$1\" not found" && exit 1
    local dir=$(echo "$1" | sed -e "s=/$==")

    for fileOrDir in $(ls "$dir"); do
        if [ -d "$dir/$fileOrDir" ]; then
            explore "$dir/$fileOrDir"
            continue
        fi
        echo "Deleting $dir/$fileOrDir"
        rm "$dir/$fileOrDir"
    done
}

explore "$1"
