#!/bin/bash
# author : lordpax
# rmc v3.3
# Supprime le contenu des dossiers et des sous-dossiers sans supprimer les dossiers eux-même

# getFile <file|dir>
function getFile() {
    [ "$1" == "" ] && exit 1

    local result=""
    local list=$(ls)

    for file in $list; do
        if [ "$1" == "file" ]; then
            [ -f "$file" ] && result="$result $file"
        elif [ "$1" == "dir" ]; then
            [ -d "$file" ] && result="$result $file"
        fi
    done

    echo "$result"
}

function explore() {
    local files=$(getFile file)
    local dirs=$(getFile dir)
    # echo "files: $files, dirs: $dirs"
    [ "$files" != "" ] && rm $files && echo "deleting of \"$files\" ..."

    for dir in $dirs; do
        echo "got to $dir"
        cd "$dir" || exit 1
        explore
        cd ..
    done
}

cd "$1" || exit 1
explore
